// ============================================================
// Docker Compose 配置文件生成
// ============================================================

/**
 * 生成 docker-compose.yml 内容
 * @param port Rocket.Chat 对外暴露的端口
 */
export function generateComposeYaml(port: number): string {
  return `# Auto-generated by openclaw-rocketchat plugin
# Do not edit manually

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    restart: unless-stopped
    ports:
      - "\${RC_PORT:-${port}}:3000"
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: "http://localhost:\${RC_PORT:-${port}}"
      OVERWRITE_SETTING_Show_Setup_Wizard: "completed"
      OVERWRITE_SETTING_Accounts_RegistrationForm: "Disabled"
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: docker.io/bitnami/mongodb:7.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
`;
}

/**
 * 生成 .env 文件内容
 */
export function generateEnvFile(port: number): string {
  return `RC_PORT=${port}\n`;
}
